
on:
  push:
    branches:
      - master
      - main

name: Compile Personal drat

jobs:
  drat:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (R-${{ matrix.config.r }})
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        config:
        - {os: windows-latest, r: '3.6', rspm: "https://packagemanager.rstudio.com/cran/latest"}
        - {os: macOS-latest,   r: '3.6', rspm: "https://packagemanager.rstudio.com/cran/latest"}
        - {os: windows-latest, r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/latest"}
        - {os: macOS-latest,   r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/latest"}
        - {os: windows-latest, r: 'release'}
        - {os: macOS-latest,   r: 'release'}
#        - {os: macos-11,   r: 'oldrel', rspm: "https://packagemanager.rstudio.com/cran/latest"}
#        - {os: macos-11,   r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}
      REPO: ${{ github.event.repository.name }}
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: gh-pages

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}

      - uses: r-lib/actions/setup-pandoc@v1
      
      - name: Install dependencies
        run: |
          install.packages(c('remotes', 'BiocManager'))
          remotes::install_github(c(
            "dipterix/drat-1",
          ), dependencies = TRUE, upgrade = 'never')
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}
      
      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      
      - name: Install dependencies
        run: |
          source("https://raw.githubusercontent.com/dipterix/drat/master/scripts/prerequisite.R")
        shell: Rscript {0}
      
      - name: Install packages
        run: |
          source("https://raw.githubusercontent.com/dipterix/drat/master/scripts/installs.R")
        shell: Rscript {0}

      - name: Compile
        shell: Rscript {0}
        run: |
          repo_dname = ""
          source("https://raw.githubusercontent.com/dipterix/drat/master/scripts/main.R")

      - name: Drat -- commit and push
        if: success()
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A *
          git add -f *.tar.gz
          git commit --allow-empty -m "Automated deploy from ${REPO}"
          git remote -v
          git push origin HEAD:gh-pages
